// Generated by build_assets.py - do not hand-edit.
// Theme table. .SET files on the card carry matching piece art;
// the wFill/wRim/wDet triples drive the 1-bit flash fallback.

#ifndef MEGACHESS_THEMES_H
#define MEGACHESS_THEMES_H

#define THEME_COUNT 5

struct Theme {
    char     name[8];
    uint16_t lightSq, darkSq, frame;
    uint16_t panelBg, card, cardHi;
    uint16_t text, textDim, accent;
    uint16_t wFill, wRim, wDet;
    uint16_t bFill, bRim, bDet;
};

static const Theme themes[THEME_COUNT] PROGMEM = {
    { "CLASSIC",
      RGB(237,234,214), RGB(125,155,118), RGB(237,234,214),
      RGB( 26, 30, 28), RGB( 42, 48, 44), RGB( 58, 66, 60),
      RGB(237,234,214), RGB(138,152,142), RGB(237,234,214),
      RGB(233,229,217), RGB( 22, 26, 22), RGB( 22, 26, 22),
      RGB( 39, 44, 38), RGB(198,204,188), RGB(116,124,110) },
    { "AMBER",
      RGB(255,158, 61), RGB(169, 63, 20), RGB(255,175, 80),
      RGB( 18, 14,  8), RGB( 53, 29, 14), RGB( 77, 41, 19),
      RGB(255,147, 69), RGB(172, 96, 50), RGB(255,147, 69),
      RGB(255,179,106), RGB( 34, 13,  5), RGB( 34, 13,  5),
      RGB( 55, 24,  9), RGB(255,146, 65), RGB(165, 78, 35) },
    { "POCKET",
      RGB(200,230,190), RGB(127,191,106), RGB(206,234,196),
      RGB( 24, 30, 22), RGB( 40, 50, 36), RGB( 56, 68, 50),
      RGB(206,234,196), RGB(126,152,118), RGB(184,224,168),
      RGB(214,237,205), RGB( 20, 36, 16), RGB( 20, 36, 16),
      RGB( 34, 50, 28), RGB(176,210,166), RGB(104,138, 94) },
    { "SLATE",
      RGB(222,228,236), RGB(108,124,146), RGB(226,232,240),
      RGB( 18, 21, 26), RGB( 34, 40, 50), RGB( 50, 58, 72),
      RGB(230,236,244), RGB(132,144,162), RGB(108,168,240),
      RGB(232,237,244), RGB( 20, 28, 40), RGB( 20, 28, 40),
      RGB( 50, 60, 74), RGB(194,208,226), RGB(116,130,150) },
    { "VECTOR",
      RGB(120,235,100), RGB( 48,120, 44), RGB(130,240,110),
      RGB(  6, 14,  8), RGB( 14, 30, 16), RGB( 22, 46, 26),
      RGB(150,255,140), RGB( 80,150, 80), RGB(100,255,100),
      RGB(175,247,165), RGB( 10, 40, 14), RGB( 10, 40, 14),
      RGB( 10, 35, 14), RGB(160,255,150), RGB( 70,140, 70) },
};

#endif // MEGACHESS_THEMES_H
