r"""
Build and run the Megachess simulator.

    python sim/build.py                      build + default scenario
    python sim/build.py 300,244 180,260 ...  build + your tap script

Steps: copy chessutil.cpp with its AVR freeMemory() removed, generate the
prototypes the Arduino build would auto-insert for Megachess.ino, compile
everything natively with MSVC, run it against SD_DATA/, and convert the PPM
frames to PNG under sim/out/.
"""
import glob
import os
import re
import shutil
import subprocess
import sys

HERE = os.path.dirname(os.path.abspath(__file__))
PROJ = os.path.dirname(HERE)
BUILD = os.path.join(HERE, "build")
OUT = os.path.join(HERE, "out")
VCVARS = r"C:\Program Files\Microsoft Visual Studio\18\Community\VC\Auxiliary\Build\vcvars64.bat"
GFX = r"C:\Users\theco\OneDrive\Documents\Arduino\libraries\Adafruit_GFX_Library"


def patched_chessutil():
    """chessutil.cpp minus <unistd.h> and the AVR freeMemory(); the sim supplies its own."""
    src = open(os.path.join(PROJ, "src", "engine", "chessutil.cpp"), encoding="utf-8").read()
    a = src.index("#include <unistd.h>")
    fn = src.index("int freeMemory() {")
    b = src.index(chr(10) + "}" + chr(10), fn)          # closing brace of the function
    b = src.index("#endif", b) + len("#endif")          # ...and its outer #ifdef ESP32 guard
    src = src[:a] + "/* freeMemory() supplied by the simulator */" + src[b:]
    os.makedirs(BUILD, exist_ok=True)
    open(os.path.join(BUILD, "chessutil.cpp"), "w", encoding="utf-8").write(src)


def prototypes():
    """The prototypes the Arduino preprocessor would insert for the .ino."""
    ino = open(os.path.join(PROJ, "Megachess.ino"), encoding="utf-8").read()
    protos = []
    for m in re.finditer(r"^((?:static\s+)?[A-Za-z_][\w:]*[\s*&]+[A-Za-z_]\w*\s*\([^;{]*\))\s*\{", ino, re.M):
        protos.append(m.group(1) + ";")
    with open(os.path.join(HERE, "megachess_protos.h"), "w", encoding="utf-8") as f:
        f.write("// generated by build.py - prototypes Arduino would auto-insert\n#pragma once\n")
        f.write("\n".join(protos) + "\n")
    return len(protos)


def compile_sim():
    shutil.copy(os.path.join(GFX, "glcdfont.c"), os.path.join(HERE, "glcdfont.c"))
    engine = [p for p in glob.glob(os.path.join(PROJ, "src", "engine", "*.cpp"))
              if not p.endswith("chessutil.cpp")]
    sources = [
        os.path.join(HERE, "main.cpp"),
        os.path.join(HERE, "panel_sim.cpp"),
        os.path.join(HERE, "arduino_sim.cpp"),
        os.path.join(HERE, "sd_sim.cpp"),
        os.path.join(PROJ, "ui.cpp"),
        os.path.join(PROJ, "storage.cpp"),
        os.path.join(PROJ, "src", "umax", "umax.cpp"),
        os.path.join(BUILD, "chessutil.cpp"),
    ] + engine
    flags = [
        "/nologo", "/EHsc", "/std:c++20", "/W1", "/wd4244", "/wd4267", "/wd4996",
        "/FI", "iso646.h",            # so `#if not X` and `and`/`or` work under MSVC
        "/DSIM=1", "/DTEENSYDUINO=1", # engine takes its no-hardware paths
        "/D_CRT_SECURE_NO_WARNINGS",
        "/I", os.path.join(HERE, "shim"),
        "/I", HERE,
        "/I", PROJ,
        "/I", os.path.join(PROJ, "src", "engine"),
        "/Fo" + BUILD + "\\",
        "/Fe" + os.path.join(BUILD, "megasim.exe"),
    ]
    cmd = 'call "%s" >nul 2>&1 && cl %s %s' % (
        VCVARS, " ".join(flags), " ".join('"%s"' % s for s in sources))
    r = subprocess.run(cmd, shell=True, cwd=BUILD, capture_output=True, text=True)
    log = r.stdout + r.stderr
    errs = [l for l in log.splitlines() if " error " in l or "error C" in l or "LNK" in l]
    if r.returncode != 0:
        print("COMPILE FAILED")
        print("\n".join(errs[:40]) or log[-4000:])
        sys.exit(1)
    print("compiled: %s" % os.path.join(BUILD, "megasim.exe"))


def run(script):
    if os.path.isdir(OUT):
        for f in glob.glob(os.path.join(OUT, "*")): os.remove(f)
    os.makedirs(OUT, exist_ok=True)
    exe = os.path.join(BUILD, "megasim.exe")
    sd = os.path.join(PROJ, "SD_DATA")
    r = subprocess.run([exe, sd, OUT] + script, capture_output=True, text=True)
    for line in r.stderr.splitlines():
        if line.startswith("frame "): print(" ", os.path.basename(line[6:]))
    with open(os.path.join(OUT, "serial.txt"), "w", encoding="utf-8") as f:
        f.write(r.stdout)                # what the sketch printed to Serial
    if r.returncode != 0:
        print("RUN FAILED (%d)" % r.returncode); print(r.stdout[-2000:]); print(r.stderr[-2000:]); sys.exit(1)

    from PIL import Image
    frames = sorted(glob.glob(os.path.join(OUT, "*.ppm")))
    for p in frames:
        Image.open(p).save(p[:-4] + ".png"); os.remove(p)
    print("%d frames -> %s" % (len(frames), OUT))


if __name__ == "__main__":
    patched_chessutil()
    print("prototypes: %d" % prototypes())
    compile_sim()
    # Default: menu, NEW GAME, pick the e2 pawn, play e2-e4, let the engine reply.
    default = ["snap:menu", "295,216", "snap:game", "180,260", "snap:pick", "180,180", "wait", "snap:after",
               "showconfirm",                       # the dialog itself
               "400,277", "220,193", "snap:kept",   # NEW then NO  -> game continues
               "400,277", "100,193", "snap:fresh"]  # NEW then YES -> new game
    run(sys.argv[1:] or default)
