r"""
Build every Megachess asset from one source, so they cannot drift apart:

  H:\PIECES\*.SET   full-colour 40x40 RGB565+alpha piece sets, one per theme
  pieces_bmp.h      1-bit flash fallback masks, used when no card is fitted
  themes_gen.h      the C theme table

Usage:  python build_assets.py [sd_root]      (default H:\)
"""
import os
import struct
import sys

import glyphs
from themes import THEMES

PX = 40
TRAY = 22
PROJ = r"C:\Users\theco\OneDrive\Documents\Arduino\Megachess"


# ---------------------------------------------------------------------------
# .SET files - one per theme, read by the sketch at runtime
# ---------------------------------------------------------------------------
def write_sets(sd_root):
    outdir = os.path.join(sd_root, "PIECES")
    os.makedirs(outdir, exist_ok=True)
    for t in THEMES:
        name, wc, bc = t[0], t[10], t[11]
        pieces = glyphs.piece_pixels(wc, bc, PX)
        blob = bytearray()
        blob += b"MCPS"
        blob += struct.pack("<HH", 1, PX)
        blob += name.encode("ascii")[:16].ljust(16, b"\0")
        blob += b"\0" * 8
        assert len(blob) == 32
        for p in pieces:
            for r, g, b, a in p:
                blob += struct.pack("<HB",
                                    ((r & 0xF8) << 8) | ((g & 0xFC) << 3) | (b >> 3),
                                    a)
        path = os.path.join(outdir, name + ".SET")
        with open(path, "wb") as f:
            f.write(blob)
        print("  %-28s %6d bytes" % (path, len(blob)))


# ---------------------------------------------------------------------------
# pieces_bmp.h - 1-bit masks. Three layers so black pieces can take a DARK
# rim and a LIGHT detail pass, same as the colour sets.
# ---------------------------------------------------------------------------
def pack(alpha_img, size, thresh):
    px = alpha_img.resize((size, size)).load() if alpha_img.size[0] != size \
        else alpha_img.load()
    stride = (size + 7) // 8
    out = []
    for y in range(size):
        row = [0] * stride
        for x in range(size):
            if px[x, y] >= thresh:
                row[x // 8] |= 0x80 >> (x % 8)
        out.extend(row)
    return out


def write_header():
    from PIL import Image
    L = glyphs._layers(PX)
    names = ["pawn", "knight", "bishop", "rook", "queen", "king"]

    # Tray silhouettes come from the Alpha SVGs (the set on the card), not
    # the Segoe glyphs: render each at TRAY px and keep its alpha as the mask.
    import svgpieces as sp
    tray = []
    for pc in ["P", "N", "B", "R", "Q", "K"]:
        svg = open(os.path.join(sp.SETS_DIR, "alpha", "w" + pc + ".svg"), encoding="utf-8").read()
        tray.append(sp.render(svg, size=TRAY).getchannel("A"))

    out = ["// Generated by build_assets.py - do not hand-edit.",
           "// 1-bit fallback masks, used when no SD card is fitted.",
           "// Three layers per piece so a black piece gets a DARK rim and a",
           "// LIGHT detail pass, instead of one heavy light outline that made",
           "// it read as white on a light square.",
           "",
           "#ifndef MEGACHESS_PIECES_H",
           "#define MEGACHESS_PIECES_H",
           "",
           "#include <Arduino.h>",
           "",
           "#define PIECE_PX %d" % PX,
           "#define TRAY_PX  %d" % TRAY,
           ""]

    total = 0
    for i, nm in enumerate(names):
        body, rim, det = L[i]
        for tag, img, sz, th in (("fill", body, PX, 110),
                                 ("rim", rim, PX, 90),
                                 ("det", det, PX, 110),
                                 ("tray", tray[i], TRAY, 100)):
            data = pack(img, sz, th)
            total += len(data)
            out.append("static const uint8_t %s_%s[] PROGMEM = {" % (nm, tag))
            for r in range(0, len(data), 10):
                out.append("  " + " ".join("0x%02X," % b for b in data[r:r + 10]))
            out.append("};")
        out.append("")

    out.append("// MicroChess types run Pawn=1 .. King=6, so index with (type - 1).")
    for tag in ("fill", "rim", "det", "tray"):
        out.append("static const uint8_t* const piece_%s[6] PROGMEM = {" % tag)
        out.append("  " + ", ".join("%s_%s" % (n, tag) for n in names))
        out.append("};")
    out += ["", "#endif // MEGACHESS_PIECES_H"]

    path = os.path.join(PROJ, "pieces_bmp.h")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("  %-28s %6d bytes of mask data" % (path, total))


# ---------------------------------------------------------------------------
# themes_gen.h
# ---------------------------------------------------------------------------
def write_themes():
    def rgb(c):
        return "RGB(%3d,%3d,%3d)" % tuple(c)

    out = ["// Generated by build_assets.py - do not hand-edit.",
           "// Theme table. .SET files on the card carry matching piece art;",
           "// the wFill/wRim/wDet triples drive the 1-bit flash fallback.",
           "",
           "#ifndef MEGACHESS_THEMES_H",
           "#define MEGACHESS_THEMES_H",
           "",
           "#define THEME_COUNT %d" % len(THEMES),
           "",
           "struct Theme {",
           "    char     name[8];",
           "    uint16_t lightSq, darkSq, frame;",
           "    uint16_t panelBg, card, cardHi;",
           "    uint16_t text, textDim, accent;",
           "    uint16_t wFill, wRim, wDet;",
           "    uint16_t bFill, bRim, bDet;",
           "};",
           "",
           "static const Theme themes[THEME_COUNT] PROGMEM = {"]
    for t in THEMES:
        (name, lsq, dsq, frame, pbg, card, chi, text, dim, acc, wc, bc) = t
        wf = tuple((wc[0][i] + wc[1][i]) // 2 for i in range(3))
        bf = tuple((bc[0][i] + bc[1][i]) // 2 for i in range(3))
        out.append('    { "%s",' % name)
        out.append("      %s, %s, %s," % (rgb(lsq), rgb(dsq), rgb(frame)))
        out.append("      %s, %s, %s," % (rgb(pbg), rgb(card), rgb(chi)))
        out.append("      %s, %s, %s," % (rgb(text), rgb(dim), rgb(acc)))
        out.append("      %s, %s, %s," % (rgb(wf), rgb(wc[2]), rgb(wc[3])))
        out.append("      %s, %s, %s }," % (rgb(bf), rgb(bc[2]), rgb(bc[3])))
    out += ["};", "", "#endif // MEGACHESS_THEMES_H"]

    path = os.path.join(PROJ, "themes_gen.h")
    with open(path, "w") as f:
        f.write("\n".join(out) + "\n")
    print("  %-28s %d themes" % (path, len(THEMES)))


def main():
    sd = sys.argv[1] if len(sys.argv) > 1 else "H:\\"
    print("piece sets ->")
    write_sets(sd)
    print("flash fallback ->")
    write_header()
    print("theme table ->")
    write_themes()


if __name__ == "__main__":
    main()
