"""Zobrist-style key table for micro-Max, as a flash array.

micro-Max hashes a position as the sum over occupied squares of
T[square + (colour & 8) + 128 * type]. Entries below 136 must be zero:
they are what an empty square contributes, and the incremental update in
D() relies on that being nothing. Above that any fixed random values do;
these are 31-bit so they are positive as a `long` on every target.
"""
import os
import random

OUT = os.path.join(os.path.dirname(__file__), "..", "src", "umax", "umax_keys.h")
N = 1035          # the highest index D() forms is 119 + 8 + 8 + 128 * 7 = 1031
ZERO_BELOW = 136

rng = random.Random(4808)
vals = [0] * ZERO_BELOW + [rng.getrandbits(31) or 1 for _ in range(N - ZERO_BELOW)]

lines = ["// Generated by tools/umax_keys.py - do not edit.",
         "#ifndef UMAX_KEYS_H", "#define UMAX_KEYS_H", "#include <Arduino.h>",
         "static const long UMAX_KEYS[%d] PROGMEM = {" % N]
for i in range(0, N, 6):
    lines.append("  " + ", ".join("%10dL" % v for v in vals[i:i + 6]) + ",")
lines += ["};", "#endif", ""]
open(OUT, "w", newline="\n").write("\n".join(lines))
print("%s: %d keys, %d zero" % (os.path.normpath(OUT), N, ZERO_BELOW))
